### ISSUE TITLE
Why EPEL?

### ISSUE THREAD

**Issue by danielo515** [robertdebock/ansible-role-collectd#3]
Hello.
Thank you very much for your collection of roles and their detailed documentation.
I noticed that, most of your roles work in a lot of linux distrubitions, however, all of them seems to depend on the epel role (like this one). As far as I know, EPEL is just for Fedora and derivates, so why would I need to use epel role if I want to apply this role to an ubuntu machine?

Thanks!

**Comment by robertdebock** [comment]
It's not required for non-RHEL systems, you are correct. I've added it to be able to use one `molecule/default/prepare.yml`. This same playbook runs on any system when the role is tested. The `epel` role skips all non-RHEL systems.
